version: '3.7'

services:
  rasa:
    image: rasa/rasa:3.5.10-full
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config:/app/config
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml
      - ./actions:/app/actions
      - ./rasa.db:/app/rasa.db
    command: ["run", "--enable-api", "--cors", "*"]
    depends_on:
      - action_server
    environment:
      - RASA_MODEL_PATH=/app/models
    entrypoint: ["bash", "-c", "rasa train && rasa run --enable-api --cors '*'"]

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: rasa run actions
